services:
  client-service:
    container_name: client-service
    build:
      dockerfile: ./.docker/remote/Dockerfile
      context: ../..
      network: host
    ports:
      - "9000:9000"
    environment:
      - GO_ENV=production
    network_mode: host
