services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "client-service"
    networks:
      - main-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 2s
      retries: 5

  client-service:
    container_name: client-service
    restart: always
    build:
      dockerfile: ./.docker/local/Dockerfile
      context: ../..
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - main-net

networks:
  main-net:
    driver: bridge


volumes:
  postgres-data:
